# Generated by Django 5.2.9 on 2026-01-10 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('announcement_type', models.CharField(default='system', max_length=20, verbose_name='公告类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统公告',
                'verbose_name_plural': '系统公告管理',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('express', '代取快递'), ('takeout', '外卖配送'), ('supermarket', '超市代购'), ('substitute', '代课服务'), ('brush', '刷课服务'), ('other', '其他服务')], max_length=20, unique=True, verbose_name='分类代码')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='分类描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '订单分类',
                'verbose_name_plural': '订单分类',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('rider', '骑手申请'), ('substitute', '代课申请'), ('brush_course', '刷课申请'), ('real_name', '实名认证')], max_length=20, verbose_name='审核类型')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='状态')),
                ('application_data', models.JSONField(verbose_name='申请数据')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
            ],
            options={
                'verbose_name': '审核申请',
                'verbose_name_plural': '审核管理',
            },
        ),
        migrations.CreateModel(
            name='BlacklistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=200, verbose_name='拉黑原因')),
                ('status', models.CharField(choices=[('active', '生效中'), ('expired', '已过期'), ('lifted', '已解除')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='到期时间')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_cases', to=settings.AUTH_USER_MODEL, verbose_name='举报人')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '黑名单记录',
                'verbose_name_plural': '黑名单管理',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message', models.TextField(blank=True, verbose_name='最后一条消息')),
                ('last_message_time', models.DateTimeField(auto_now=True, verbose_name='最后消息时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='参与者')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话管理',
                'ordering': ['-last_message_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.conversation', verbose_name='会话')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息管理',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order', '订单通知'), ('payment', '支付通知'), ('system', '系统通知'), ('promotion', '推广通知')], max_length=20, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('title', models.CharField(max_length=200, verbose_name='订单标题')),
                ('description', models.TextField(verbose_name='订单描述')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('status', models.CharField(choices=[('pending', '待接单'), ('accepted', '已接单'), ('processing', '进行中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='接单时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rider_orders', to=settings.AUTH_USER_MODEL, verbose_name='骑手')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ordercategory', verbose_name='订单分类')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_grab_enabled', models.BooleanField(default=False, verbose_name='是否启用自动接单')),
                ('max_orders_per_hour', models.PositiveIntegerField(default=5, verbose_name='每小时最大接单数')),
                ('max_orders_total', models.PositiveIntegerField(default=20, verbose_name='最大接单总数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('categories', models.ManyToManyField(blank=True, to='api.ordercategory', verbose_name='可接订单分类')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_settings', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '骑手设置',
                'verbose_name_plural': '骑手设置',
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('bug', '问题反馈'), ('suggestion', '功能建议'), ('complaint', '投诉建议'), ('other', '其他')], max_length=20, verbose_name='反馈类型')),
                ('title', models.CharField(max_length=200, verbose_name='反馈标题')),
                ('content', models.TextField(verbose_name='反馈内容')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系方式')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='状态')),
                ('reply', models.TextField(blank=True, verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='绑定手机号')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('student_id', models.CharField(max_length=20, verbose_name='学号')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否实名认证')),
                ('credit_score', models.IntegerField(default=100, verbose_name='诚信度分数')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='是否在黑名单')),
                ('blacklist_reason', models.TextField(blank=True, verbose_name='黑名单原因')),
                ('blacklist_until', models.DateTimeField(blank=True, null=True, verbose_name='黑名单到期时间')),
                ('last_login_time', models.DateTimeField(auto_now=True, verbose_name='最后登录时间')),
                ('last_logout_time', models.DateTimeField(blank=True, null=True, verbose_name='最后退出时间')),
                ('login_count', models.IntegerField(default=0, verbose_name='登录次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('avatar_url', models.URLField(blank=True, max_length=500, verbose_name='头像URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户资料',
                'verbose_name_plural': '用户资料管理',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='余额')),
                ('frozen_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='冻结余额')),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总收入')),
                ('total_expenditure', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='总支出')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户钱包',
                'verbose_name_plural': '用户钱包管理',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', '收入'), ('expenditure', '支出'), ('refund', '退款'), ('withdraw', '提现')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='金额')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.wallet', verbose_name='钱包')),
            ],
            options={
                'verbose_name': '交易记录',
                'verbose_name_plural': '交易记录管理',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderGrabRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grabbed_at', models.DateTimeField(auto_now_add=True, verbose_name='接单时间')),
                ('completed', models.BooleanField(default=False, verbose_name='是否完成')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grab_records', to='api.order', verbose_name='订单')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grab_records', to=settings.AUTH_USER_MODEL, verbose_name='骑手')),
            ],
            options={
                'verbose_name': '骑手接单记录',
                'verbose_name_plural': '骑手接单记录',
                'ordering': ['-grabbed_at'],
                'unique_together': {('user', 'order')},
            },
        ),
    ]
