# Generated by Django 5.2.8 on 2025-12-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'ordering': ['-order', '-create_time'], 'verbose_name': '欢迎页', 'verbose_name_plural': '欢迎页管理'},
        ),
        migrations.AlterField(
            model_name='welcome',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='img',
            field=models.ImageField(default='welcome/slash.png', upload_to='welcome/', verbose_name='欢迎图片'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='welcome',
            name='order',
            field=models.IntegerField(default=0, verbose_name='排序'),
        ),
    ]
