# Generated by Django 5.2.9 on 2025-12-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_alter_welcome_options_alter_welcome_create_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='welcome',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否启用'),
        ),
        migrations.AddField(
            model_name='welcome',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='标题'),
        ),
    ]
